spring:
  application:
    name: measure

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://auth.christiandellisanti.uk/realms/measurestream
  #data:
  #  mongodb:
  #    uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}
      # Se vuoi definire altre opzioni come il database di default, puoi farlo qui:
  #    database: ${MONGO_INITDB_DATABASE}

  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: measurestream
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8080




