spring:
  application:
    name: measure

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://172.20.0.22:8080/realms/measurestream
  data:
    mongodb:
      uri: mongodb://root:secret@mongodb:27017/mydatabase
      # Se vuoi definire altre opzioni come il database di default, puoi farlo qui:
      database: mydatabase
server:
  port: 8080
